/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kata.word.search

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {

    @Test fun testSomeLibraryMethod() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
